# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - nav_debug/**  # Exclude debug/test folder
  errors:
    # Ignore unused code warnings - tree shaking removes them in release
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    unused_import: ignore
    deprecated_member_use: ignore
    constant_identifier_names: ignore
    unnecessary_import: ignore
    depend_on_referenced_packages: ignore
    unused_catch_stack: ignore
    unused_shown_name: ignore
    dead_code: ignore
    todo: ignore

linter:
  rules:
    # Disabled - too noisy for rapid development
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    curly_braces_in_flow_control_structures: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
