-- ============================================================================
-- TORO - MEXICO SUPPORT: Pricing Zones and Rules
-- Migration 008
-- ============================================================================

-- ============================================================================
-- PRICING ZONES TABLE
-- Geographic zones for pricing in Mexico
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pricing_zones_mx (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    state_code TEXT NOT NULL, -- 'CDMX', 'JAL', 'NL'

    -- Geographic area (polygon)
    area geography(MULTIPOLYGON, 4326),

    -- Center point for reference
    center_lat DECIMAL(10,8),
    center_lng DECIMAL(11,8),

    -- Metadata
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Spatial index
CREATE INDEX IF NOT EXISTS idx_pricing_zones_mx_area
ON public.pricing_zones_mx USING GIST (area);

CREATE INDEX IF NOT EXISTS idx_pricing_zones_mx_state
ON public.pricing_zones_mx(state_code);

-- RLS
ALTER TABLE public.pricing_zones_mx ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read pricing zones" ON public.pricing_zones_mx
    FOR SELECT USING (true);

-- ============================================================================
-- PRICING RULES TABLE
-- Pricing rules per zone and service type
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pricing_rules_mx (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES public.pricing_zones_mx(id) ON DELETE CASCADE,
    service_type TEXT NOT NULL, -- 'ride', 'delivery', 'carpool'
    vehicle_type TEXT DEFAULT 'standard', -- 'standard', 'premium', 'moto'

    -- Base pricing
    base_fare DECIMAL(10,2) NOT NULL, -- Tarifa base
    per_km DECIMAL(10,2) NOT NULL, -- Por kilómetro
    per_min DECIMAL(10,2) NOT NULL, -- Por minuto
    min_fare DECIMAL(10,2) NOT NULL, -- Tarifa mínima

    -- Fees
    booking_fee DECIMAL(10,2) DEFAULT 0.00, -- Cargo por servicio
    cancellation_fee DECIMAL(10,2) DEFAULT 0.00, -- Cargo por cancelación

    -- Multipliers
    night_multiplier DECIMAL(5,2) DEFAULT 1.00, -- Multiplicador nocturno
    night_start_hour INTEGER DEFAULT 22, -- Hora inicio tarifa nocturna
    night_end_hour INTEGER DEFAULT 6, -- Hora fin tarifa nocturna

    weekend_multiplier DECIMAL(5,2) DEFAULT 1.00, -- Multiplicador fin de semana
    rain_multiplier DECIMAL(5,2) DEFAULT 1.00, -- Multiplicador lluvia (manual o API clima)

    -- Dynamic pricing
    surge_enabled BOOLEAN DEFAULT TRUE,
    max_surge_multiplier DECIMAL(5,2) DEFAULT 2.00,

    -- Platform split
    platform_fee_percent DECIMAL(5,2) DEFAULT 20.00, -- Comisión plataforma
    driver_percent DECIMAL(5,2) DEFAULT 80.00, -- Porcentaje driver

    -- Currency
    currency TEXT DEFAULT 'MXN',

    -- Validity
    effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    effective_to TIMESTAMPTZ, -- NULL = currently active

    -- Metadata
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pricing_rules_mx_zone
ON public.pricing_rules_mx(zone_id, service_type);

CREATE INDEX IF NOT EXISTS idx_pricing_rules_mx_active
ON public.pricing_rules_mx(zone_id, service_type, effective_from DESC)
WHERE effective_to IS NULL AND is_active = TRUE;

-- RLS
ALTER TABLE public.pricing_rules_mx ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read pricing rules" ON public.pricing_rules_mx
    FOR SELECT USING (true);

-- ============================================================================
-- RIDE FARES TABLE
-- Detailed fare breakdown per ride
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.ride_fares (
    ride_id UUID PRIMARY KEY REFERENCES public.rides(id) ON DELETE CASCADE,

    -- Pricing rule used
    pricing_rule_id BIGINT REFERENCES public.pricing_rules_mx(id),
    zone_id BIGINT REFERENCES public.pricing_zones_mx(id),

    -- Currency
    currency TEXT NOT NULL DEFAULT 'MXN',
    fx_rate_used DECIMAL(12,6),

    -- Distance and time
    distance_km DECIMAL(10,3),
    duration_min DECIMAL(10,2),

    -- Fare breakdown
    base_fare DECIMAL(10,2),
    distance_amount DECIMAL(10,2), -- distance_km * per_km
    time_amount DECIMAL(10,2), -- duration_min * per_min
    booking_fee DECIMAL(10,2) DEFAULT 0.00,

    -- Multipliers applied
    night_multiplier_applied DECIMAL(5,2) DEFAULT 1.00,
    surge_multiplier_applied DECIMAL(5,2) DEFAULT 1.00,
    surge_amount DECIMAL(10,2) DEFAULT 0.00,

    -- Extras
    tolls DECIMAL(10,2) DEFAULT 0.00,
    tip_amount DECIMAL(10,2) DEFAULT 0.00,

    -- Tax (IVA)
    subtotal DECIMAL(10,2) NOT NULL,
    tax_rate DECIMAL(5,4) DEFAULT 0.16,
    tax_amount DECIMAL(10,2) NOT NULL,

    -- Total
    total DECIMAL(10,2) NOT NULL,

    -- Platform split
    platform_fee DECIMAL(10,2),
    driver_earnings DECIMAL(10,2),

    -- Retentions (for Mexico)
    isr_retained DECIMAL(10,2) DEFAULT 0.00,
    iva_retained DECIMAL(10,2) DEFAULT 0.00,
    driver_net DECIMAL(10,2), -- After retentions

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ride_fares_zone ON public.ride_fares(zone_id);
CREATE INDEX IF NOT EXISTS idx_ride_fares_created ON public.ride_fares(created_at DESC);

-- RLS
ALTER TABLE public.ride_fares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Drivers and riders can view relevant fares" ON public.ride_fares
    FOR SELECT USING (
        ride_id IN (
            SELECT id FROM public.rides
            WHERE driver_id = auth.uid()
        )
    );

-- ============================================================================
-- INSERT DEFAULT ZONES AND PRICING FOR MEXICO
-- ============================================================================

-- CDMX Zone
INSERT INTO public.pricing_zones_mx (name, state_code, center_lat, center_lng, description)
VALUES
    ('CDMX Centro', 'CDMX', 19.4326, -99.1332, 'Ciudad de México - Zona Centro'),
    ('CDMX Norte', 'CDMX', 19.5000, -99.1500, 'Ciudad de México - Zona Norte'),
    ('CDMX Sur', 'CDMX', 19.3500, -99.1600, 'Ciudad de México - Zona Sur'),
    ('Guadalajara Centro', 'JAL', 20.6597, -103.3496, 'Guadalajara - Zona Centro'),
    ('Monterrey Centro', 'NL', 25.6866, -100.3161, 'Monterrey - Zona Centro')
ON CONFLICT DO NOTHING;

-- Pricing rules for CDMX
INSERT INTO public.pricing_rules_mx (
    zone_id, service_type, vehicle_type,
    base_fare, per_km, per_min, min_fare,
    booking_fee, cancellation_fee,
    night_multiplier, night_start_hour, night_end_hour,
    weekend_multiplier, max_surge_multiplier,
    platform_fee_percent, driver_percent, currency
)
SELECT
    z.id,
    service.type,
    'standard',
    CASE service.type
        WHEN 'ride' THEN 35.00
        WHEN 'delivery' THEN 30.00
        WHEN 'carpool' THEN 25.00
    END,
    CASE service.type
        WHEN 'ride' THEN 8.50
        WHEN 'delivery' THEN 7.00
        WHEN 'carpool' THEN 5.00
    END,
    CASE service.type
        WHEN 'ride' THEN 2.50
        WHEN 'delivery' THEN 2.00
        WHEN 'carpool' THEN 1.50
    END,
    CASE service.type
        WHEN 'ride' THEN 50.00
        WHEN 'delivery' THEN 45.00
        WHEN 'carpool' THEN 35.00
    END,
    5.00, -- booking fee
    25.00, -- cancellation fee
    1.25, -- night multiplier
    22, 6, -- night hours
    1.10, -- weekend multiplier
    2.00, -- max surge
    20.00, 80.00, -- platform/driver split
    'MXN'
FROM public.pricing_zones_mx z
CROSS JOIN (VALUES ('ride'), ('delivery'), ('carpool')) AS service(type)
WHERE z.state_code = 'CDMX'
ON CONFLICT DO NOTHING;

-- Pricing rules for Guadalajara (slightly lower)
INSERT INTO public.pricing_rules_mx (
    zone_id, service_type, vehicle_type,
    base_fare, per_km, per_min, min_fare,
    booking_fee, cancellation_fee,
    night_multiplier, weekend_multiplier, max_surge_multiplier,
    platform_fee_percent, driver_percent, currency
)
SELECT
    z.id,
    'ride',
    'standard',
    30.00, 7.50, 2.00, 45.00,
    5.00, 20.00,
    1.20, 1.10, 1.80,
    20.00, 80.00, 'MXN'
FROM public.pricing_zones_mx z
WHERE z.state_code = 'JAL'
ON CONFLICT DO NOTHING;

-- Pricing rules for Monterrey
INSERT INTO public.pricing_rules_mx (
    zone_id, service_type, vehicle_type,
    base_fare, per_km, per_min, min_fare,
    booking_fee, cancellation_fee,
    night_multiplier, weekend_multiplier, max_surge_multiplier,
    platform_fee_percent, driver_percent, currency
)
SELECT
    z.id,
    'ride',
    'standard',
    32.00, 8.00, 2.20, 48.00,
    5.00, 22.00,
    1.20, 1.10, 1.80,
    20.00, 80.00, 'MXN'
FROM public.pricing_zones_mx z
WHERE z.state_code = 'NL'
ON CONFLICT DO NOTHING;

-- ============================================================================
-- FUNCTION: Get pricing for location
-- ============================================================================

CREATE OR REPLACE FUNCTION get_pricing_for_location(
    p_lat DECIMAL,
    p_lng DECIMAL,
    p_service_type TEXT DEFAULT 'ride',
    p_vehicle_type TEXT DEFAULT 'standard'
)
RETURNS TABLE (
    zone_id BIGINT,
    zone_name TEXT,
    state_code TEXT,
    base_fare DECIMAL,
    per_km DECIMAL,
    per_min DECIMAL,
    min_fare DECIMAL,
    booking_fee DECIMAL,
    night_multiplier DECIMAL,
    weekend_multiplier DECIMAL,
    max_surge_multiplier DECIMAL,
    platform_fee_percent DECIMAL,
    currency TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        z.id,
        z.name,
        z.state_code,
        pr.base_fare,
        pr.per_km,
        pr.per_min,
        pr.min_fare,
        pr.booking_fee,
        pr.night_multiplier,
        pr.weekend_multiplier,
        pr.max_surge_multiplier,
        pr.platform_fee_percent,
        pr.currency
    FROM public.pricing_zones_mx z
    JOIN public.pricing_rules_mx pr ON pr.zone_id = z.id
    WHERE z.is_active = TRUE
    AND pr.is_active = TRUE
    AND pr.service_type = p_service_type
    AND pr.vehicle_type = p_vehicle_type
    AND pr.effective_to IS NULL
    AND (
        z.area IS NULL -- If no polygon, match by state proximity
        OR ST_Contains(z.area::geometry, ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326))
    )
    ORDER BY
        CASE WHEN z.area IS NOT NULL THEN 0 ELSE 1 END, -- Prefer zones with polygons
        ST_Distance(
            ST_SetSRID(ST_MakePoint(z.center_lng, z.center_lat), 4326)::geography,
            ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography
        )
    LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- FUNCTION: Calculate ride fare
-- ============================================================================

CREATE OR REPLACE FUNCTION calculate_ride_fare(
    p_pickup_lat DECIMAL,
    p_pickup_lng DECIMAL,
    p_dropoff_lat DECIMAL,
    p_dropoff_lng DECIMAL,
    p_distance_km DECIMAL,
    p_duration_min DECIMAL,
    p_service_type TEXT DEFAULT 'ride',
    p_vehicle_type TEXT DEFAULT 'standard',
    p_is_night BOOLEAN DEFAULT FALSE,
    p_is_weekend BOOLEAN DEFAULT FALSE,
    p_surge_multiplier DECIMAL DEFAULT 1.00,
    p_tolls DECIMAL DEFAULT 0.00
)
RETURNS TABLE (
    zone_id BIGINT,
    zone_name TEXT,
    currency TEXT,
    base_fare DECIMAL,
    distance_amount DECIMAL,
    time_amount DECIMAL,
    booking_fee DECIMAL,
    subtotal_before_multipliers DECIMAL,
    night_multiplier DECIMAL,
    weekend_multiplier DECIMAL,
    surge_multiplier DECIMAL,
    surge_amount DECIMAL,
    tolls DECIMAL,
    subtotal DECIMAL,
    tax_rate DECIMAL,
    tax_amount DECIMAL,
    total DECIMAL,
    platform_fee DECIMAL,
    driver_earnings DECIMAL,
    min_fare_applied BOOLEAN
) AS $$
DECLARE
    v_pricing RECORD;
    v_base DECIMAL;
    v_distance_amount DECIMAL;
    v_time_amount DECIMAL;
    v_subtotal_pre DECIMAL;
    v_night_mult DECIMAL := 1.00;
    v_weekend_mult DECIMAL := 1.00;
    v_surge_amount DECIMAL := 0.00;
    v_subtotal DECIMAL;
    v_tax_rate DECIMAL := 0.16;
    v_tax DECIMAL;
    v_total DECIMAL;
    v_platform_fee DECIMAL;
    v_driver_earnings DECIMAL;
    v_min_fare_applied BOOLEAN := FALSE;
BEGIN
    -- Get pricing for pickup location
    SELECT * INTO v_pricing
    FROM get_pricing_for_location(p_pickup_lat, p_pickup_lng, p_service_type, p_vehicle_type);

    IF v_pricing IS NULL THEN
        -- Default pricing if no zone found
        v_pricing := ROW(
            0::BIGINT, 'Default'::TEXT, 'MX'::TEXT,
            35.00, 8.50, 2.50, 50.00, 5.00,
            1.25, 1.10, 2.00, 20.00, 'MXN'::TEXT
        );
    END IF;

    -- Calculate base amounts
    v_base := v_pricing.base_fare;
    v_distance_amount := p_distance_km * v_pricing.per_km;
    v_time_amount := p_duration_min * v_pricing.per_min;
    v_subtotal_pre := v_base + v_distance_amount + v_time_amount + v_pricing.booking_fee;

    -- Apply multipliers
    IF p_is_night THEN
        v_night_mult := v_pricing.night_multiplier;
    END IF;

    IF p_is_weekend THEN
        v_weekend_mult := v_pricing.weekend_multiplier;
    END IF;

    -- Apply surge (capped at max)
    IF p_surge_multiplier > v_pricing.max_surge_multiplier THEN
        p_surge_multiplier := v_pricing.max_surge_multiplier;
    END IF;

    -- Calculate subtotal with multipliers
    v_subtotal := v_subtotal_pre * v_night_mult * v_weekend_mult * p_surge_multiplier;
    v_surge_amount := v_subtotal - (v_subtotal_pre * v_night_mult * v_weekend_mult);

    -- Add tolls
    v_subtotal := v_subtotal + p_tolls;

    -- Apply minimum fare
    IF v_subtotal < v_pricing.min_fare THEN
        v_subtotal := v_pricing.min_fare;
        v_min_fare_applied := TRUE;
    END IF;

    -- Calculate tax
    v_tax := ROUND(v_subtotal * v_tax_rate, 2);
    v_total := v_subtotal + v_tax;

    -- Calculate split
    v_platform_fee := ROUND(v_subtotal * (v_pricing.platform_fee_percent / 100), 2);
    v_driver_earnings := v_subtotal - v_platform_fee;

    RETURN QUERY SELECT
        v_pricing.zone_id,
        v_pricing.zone_name,
        v_pricing.currency,
        v_base,
        v_distance_amount,
        v_time_amount,
        v_pricing.booking_fee,
        v_subtotal_pre,
        v_night_mult,
        v_weekend_mult,
        p_surge_multiplier,
        v_surge_amount,
        p_tolls,
        v_subtotal,
        v_tax_rate,
        v_tax,
        v_total,
        v_platform_fee,
        v_driver_earnings,
        v_min_fare_applied;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- REALTIME
-- ============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.pricing_rules_mx;
