-- ============================================================================
-- MIGRATION: Multi-Stripe Support for Mexico
-- Date: 2026-01-30
-- Description: Add provider column to driver_stripe_accounts for US/MX support
-- ============================================================================

-- 1. Add provider column to driver_stripe_accounts
ALTER TABLE public.driver_stripe_accounts
ADD COLUMN IF NOT EXISTS provider text NOT NULL DEFAULT 'us';

-- 2. Add is_default column for multiple accounts
ALTER TABLE public.driver_stripe_accounts
ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false;

-- 3. Update existing records to have provider = 'us'
UPDATE public.driver_stripe_accounts
SET provider = 'us'
WHERE provider IS NULL OR provider = '';

-- 4. Drop the existing UNIQUE constraint on driver_id if it exists
DO $$
BEGIN
  -- Try to drop the constraint (it may have different names)
  ALTER TABLE public.driver_stripe_accounts
    DROP CONSTRAINT IF EXISTS driver_stripe_accounts_driver_id_key;
  ALTER TABLE public.driver_stripe_accounts
    DROP CONSTRAINT IF EXISTS driver_stripe_accounts_driver_id_unique;
EXCEPTION
  WHEN undefined_object THEN
    NULL; -- Constraint doesn't exist, ignore
END $$;

-- 5. Create new UNIQUE constraint on (driver_id, provider)
ALTER TABLE public.driver_stripe_accounts
ADD CONSTRAINT driver_stripe_accounts_driver_provider_unique
UNIQUE (driver_id, provider);

-- 6. Create index for provider queries
CREATE INDEX IF NOT EXISTS idx_driver_stripe_accounts_provider
ON public.driver_stripe_accounts(provider);

-- 7. Create index for active accounts
CREATE INDEX IF NOT EXISTS idx_driver_stripe_accounts_active
ON public.driver_stripe_accounts(driver_id, is_active)
WHERE is_active = true;

-- 8. Create FX rates table for currency conversion
CREATE TABLE IF NOT EXISTS public.fx_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_currency text NOT NULL,
  quote_currency text NOT NULL,
  rate numeric(12,6) NOT NULL,
  source text,
  fetched_at timestamptz NOT NULL DEFAULT now()
);

-- Index for fx_rates lookups
CREATE INDEX IF NOT EXISTS idx_fx_rates_currencies
ON public.fx_rates(base_currency, quote_currency, fetched_at DESC);

-- RLS for fx_rates
ALTER TABLE public.fx_rates ENABLE ROW LEVEL SECURITY;

-- Everyone can read fx rates
CREATE POLICY "fx_rates_select" ON public.fx_rates
FOR SELECT TO authenticated USING (true);

-- Only service role can insert/update fx rates
CREATE POLICY "fx_rates_service_insert" ON public.fx_rates
FOR INSERT TO service_role WITH CHECK (true);

-- 9. Insert initial FX rates
INSERT INTO public.fx_rates (base_currency, quote_currency, rate, source)
VALUES
  ('MXN', 'USD', 0.058824, 'manual_seed'),
  ('USD', 'MXN', 17.00, 'manual_seed')
ON CONFLICT DO NOTHING;

-- 10. Add currency columns to rides if not exist
ALTER TABLE public.rides
ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USD';

ALTER TABLE public.rides
ADD COLUMN IF NOT EXISTS fx_rate_applied numeric(12,6);

-- 11. Function to get current FX rate
CREATE OR REPLACE FUNCTION get_current_fx_rate(p_base text, p_quote text)
RETURNS numeric AS $$
DECLARE
  v_rate numeric;
BEGIN
  SELECT rate INTO v_rate
  FROM public.fx_rates
  WHERE base_currency = p_base AND quote_currency = p_quote
  ORDER BY fetched_at DESC
  LIMIT 1;

  RETURN COALESCE(v_rate, 1.0);
END;
$$ LANGUAGE plpgsql;

-- 12. Function to convert currency
CREATE OR REPLACE FUNCTION convert_currency(
  p_amount numeric,
  p_from text,
  p_to text
)
RETURNS numeric AS $$
DECLARE
  v_rate numeric;
BEGIN
  IF p_from = p_to THEN
    RETURN p_amount;
  END IF;

  v_rate := get_current_fx_rate(p_from, p_to);
  RETURN ROUND(p_amount * v_rate, 2);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Stripe Mexico Configuration Notes:
--
-- Environment variables needed in Supabase Edge Functions:
--   STRIPE_US_SECRET_KEY=sk_live_xxx (existing)
--   STRIPE_US_PUBLISHABLE_KEY=pk_live_xxx (existing)
--   STRIPE_MX_SECRET_KEY=sk_test_51SvLIZJL6dZ5MsYqJsjZy6OWsk5DMzIovXGJofFvFSNG4q7dfcCAEDDtWb7hBoWn05oBZz3biaoIoHdxqvjQoNXn00iwWNE7t7
--   STRIPE_MX_PUBLISHABLE_KEY=pk_test_51SvLIZJL6dZ5MsYqvDAUIhO74kK7r93XLcYSlTLP5oupLb6lwhLe4XppoSOUWuhkNenCvcdo6xQ7DBkLO3yWRpVT000m01MebB
-- ============================================================================

COMMENT ON COLUMN public.driver_stripe_accounts.provider IS 'Stripe provider: us for United States, mx for Mexico';
COMMENT ON COLUMN public.driver_stripe_accounts.is_default IS 'Whether this is the default account for the driver';
